
init_config:
  loader: core
  use_device_id_as_hostname: true
  profiles:
    custom-profile:
      definition_file: test_profile.yaml
      
instances:

  - ip_address: 172.1.1.3
    snmp_version: 2
    community_string: nasuni-filer
    profile: custom-profile
    tags:
      - "location:boston"  
  
  - network_address: 172.1.1.1/28
    snmp_version: 2
    port: 161
    community_string: nasuni-filer
    profile: custom-profile
    tags:
    - "auto-discovery:auto-discovered-device"